#!/usr/bin/env bash
# Generated by setup.sh -> /workspace/start.sh. Starts the enhancer web UI on 0.0.0.0:7860.
set -euo pipefail
WORKSPACE="@WORKSPACE@"
REPO_DIR="@REPO_DIR@"
export PATH="$WORKSPACE/bin:$PATH"
export HF_HOME="$WORKSPACE/hf"
export ENHANCE_WORKSPACE="$WORKSPACE"
export PYTHONUNBUFFERED=1
export GRADIO_ANALYTICS_ENABLED=0
# ENHANCE_AUTH="user:pass" protects the UI + API; ENHANCE_PORT overrides 7860.
# Pod env vars set in RunPod are not visible to SSH shells, so also read them from /workspace/.env
# (lines like ENHANCE_AUTH=user:pass). Values already in the environment win.
if [[ -f "$WORKSPACE/.env" ]]; then
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ "$line" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]] || continue
    key="${line%%=*}"
    [[ -z "${!key:-}" ]] && export "$line"
  done < "$WORKSPACE/.env"
fi

# apt packages live on the ephemeral container disk; restore them after a pod reset.
if ! command -v ffmpeg >/dev/null; then
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq && apt-get install -y -qq --no-install-recommends ffmpeg libgl1 libglib2.0-0 >/dev/null
fi

cd "$REPO_DIR"
exec "$WORKSPACE/venvs/fast/bin/python" -m app.server
